[tox]
envlist =
    # Django pre-release
    py{312,313,314}-djpre

    # Django 5.2
    py{310,311,312,313,314}-dj52,
    # Django 6.0 and 6.1
    py{312,313,314}-dj{60,61},

[virtualenv]
discovery = pyenv

[testenv]
deps =
    pytest-django
    xmltodict
    PyYAML
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1,<6.2
    djpre: Django
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONPATH = {toxinidir}
changedir = tests
commands = pytest {posargs}

[testenv:py{312,313,314}-djpre]
pip_pre = True
deps =
    pytest-django
    xmltodict
    PyYAML
    Django
